CREATE SEQUENCE ACCOUNT_SEQ;

CREATE SEQUENCE OPERATION_SEQ;

CREATE TABLE ACCOUNT
(
ID number NOT NULL, 
ACCOUNT_NUMBER NUMBER NOT NULL,
BALANCE NUMBER NOT NULL,
CONSTRAINT PK_ACCOUNT PRIMARY KEY (ID) USING INDEX
);

CREATE TABLE OPERATION
(
ID number NOT NULL, 
ACCOUNT_ID NUMBER NOT NULL,
TYPE VARCHAR2(30) NOT NULL,
AMOUNT NUMBER NOT NULL,
CONSTRAINT PK_OPERATION PRIMARY KEY (ID) USING INDEX,
CONSTRAINT FK_ACCOUNT_ID FOREIGN KEY (ACCOUNT_ID) REFERENCES ACCOUNT(ID)
)
;


